### ISSUE TITLE
Failed to run with `TypeError: globals.includes is not a function`

### ISSUE THREAD

**Issue by checketts** [xvik/generator-lib-java#2]
I'm new to Yeoman. I ran `yo lib-java` and answered all the questions. After the `Enable code quality checks` question it errored out with:

I'm running on OSX.

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: globals.includes is not a function
    at /usr/local/lib/node_modules/generator-lib-java/node_modules/yo-java-helper/src/index.js:162:25
    at Array.forEach (native)
    at $saveConfiguration (/usr/local/lib/node_modules/generator-lib-java/node_modules/yo-java-helper/src/index.js:159:19)
    at configuring (/usr/local/lib/node_modules/generator-lib-java/app/index.js:260:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-lib-java/node_modules/yeoman-generator/lib/index.js:408:23)
    at /usr/local/lib/node_modules/generator-lib-java/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-lib-java/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-lib-java/node_modules/yeoman-generator/lib/index.js:409:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by checketts** [comment]
I was on Node v5.5.0. Upgrading to Node v7.7.1 Fixed it for me

**Comment by xvik** [comment]
Love such self-closing issues :)
Honestly, I was hoping npm will consider required node version in package.json and install older version for older nodes.. seems not :(
